### ISSUE TITLE
React Native Web: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by michaelhly** [magiclabs/magic-js#322]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
Nothing happens when I run `const didToken = await m.auth.loginWithSMS({ phoneNumber });` on React native web.

### 🧩 Steps to Reproduce

1. Create React Native app with `expo init`
2. Set up magic relayer:
```js
    <>
      <StatusBar style="light" />
      <m.Relayer />
      <Navigation colorScheme={colorScheme} />
    </>
```
3. Create an app with this handler:
```js
 const handleSubmit = async () => {
    console.log({ phoneNumber });
    try {
      const didToken = await m.auth.loginWithSMS({ phoneNumber });
      // TODO(michael): Validate the didToken with server, then set user context
    } catch (e) {
      const error = e as Error;
      // TODO(michael): Log error to sentry
      console.error(error);
      setLoginError(error);
      return;
    }

    navigate("LoggedInScreen");
```
}

### 🤔 Expected behavior
Prompt magic webview to enter SMS confirmation code

### 😮 Actual behavior
Nothing ...

Stack trace:
```
index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
    at WebView
    at div
    at http://localhost:19006/static/js/bundle.js:96600:25
    at U.Relayer (http://localhost:19006/static/js/bundle.js:10357:8024)
    at AppWrapper (http://localhost:19006/static/js/bundle.js:5985:81)
    at UserProvider (http://localhost:19006/static/js/bundle.js:6538:23)
    at Provider (http://localhost:19006/static/js/bundle.js:121351:31)
    at div
    at http://localhost:19006/static/js/bundle.js:96600:25
    at NativeSafeAreaProvider (http://localhost:19006/static/js/bundle.js:87454:23)
    at SafeAreaProvider (http://localhost:19006/static/js/bundle.js:87651:23)
    at App (http://localhost:19006/static/js/bundle.js:5939:65)
    at ExpoRootComponent (http://localhost:19006/static/js/bundle.js:32123:83)
    at div
    at http://localhost:19006/static/js/bundle.js:96600:25
    at div
    at http://localhost:19006/static/js/bundle.js:96600:25
    at AppContainer (http://localhost:19006/static/js/bundle.js:88460:24)
```

### 💻 Code Sample
See steps to reproduce.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  "@magic-sdk/react-native": "^8.2.1"
| Browser          |  Chrome Version 102.0.5005.61 (Official Build) (arm64)
| `yarn`           | 1.22.18
| Operating System | MacOS Monterey 12.2.1

**Comment by Ethella** [comment]
Do you use the react-native web? I believe that's not officially supported yet

**Comment by michaelhly** [comment]
@Ethella the magic react native SDK does not support web?

**Comment by Ethella** [comment]
> @Ethella the magic react native SDK doesn’t work in a web browser? Only mobile?

Yes, that's right
