### ISSUE TITLE
Error: Magic RPC Error: [-32603] Internal error: JSON-RPC error. (Login with SMS)

### ISSUE THREAD

**Issue by michaelhly** [magiclabs/magic-js#323]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
RPC error when trying to invoke `sdk.auth.loginWithSMS({ phoneNumber })`.

[Description of the bug.]

### 🧩 Steps to Reproduce

1. Create React Native app with `expo init`
2. Set up the proper Magic provider
- using `"magic-sdk"` for web
- `@magic-sdk/react-native` for mobile.

3. Invoke SMS handler written as follow:
```js
 const handleSubmit = async () => {
    console.log({ phoneNumber });
    try {
      const didToken = await m.auth.loginWithSMS({ phoneNumber });
      // TODO(michael): Validate the didToken with server, then set user context
    } catch (e) {
      const error = e as Error;
      // TODO(michael): Log error to sentry
      console.error(error);
      setLoginError(error);
      return;
    }

    navigate("LoggedInScreen");
}
```

### 🤔 Expected behavior
Send SMS message to mobile device

### 😮 Actual behavior
Web:
```
Failed to load resource: the server responded with a status of 400 ()

Error: Magic RPC Error: [-32603] Internal error: JSON-RPC error. 
  at index.js:5:1
console.<computed> @ index.js:1
Promise.then (async)
(anonymous) @ index.js:5
invoke @ regeneratorRuntime.js:129
(anonymous) @ regeneratorRuntime.js:148
callInvokeWithMethodAndArg @ regeneratorRuntime.js:147
AsyncIterator._invoke @ regeneratorRuntime.js:152
(anonymous) @ regeneratorRuntime.js:117
exports.async @ regeneratorRuntime.js:238
_callee @ PhoneScreen.tsx:21
onClick @ PressResponder.js:364
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

React Native:
```
Error: ENOENT: no such file or directory, open '/Users/michaelhly/Projects/my-app/http:/192.168.1.190:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/michaelhly/Projects/my-app/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/michaelhly/Projects/my-app/node_modules/metro/src/Server.js:1022:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server._processRequest (/Users/michaelhly/Projects/my-app/node_modules/metro/src/Server.js:429:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/michaelhly/Projects/my-app/http:/192.168.1.190:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
}
Error: ENOENT: no such file or directory, open '/Users/michaelhly/Projects/my-app/http:/192.168.1.190:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/michaelhly/Projects/my-app/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/michaelhly/Projects/my-app/node_modules/metro/src/Server.js:1022:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server._processRequest (/Users/michaelhly/Projects/my-app/node_modules/metro/src/Server.js:429:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/michaelhly/Projects/my-app/http:/192.168.1.190:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
}

Magic RPC Error: [-32603] Internal error: JSON-RPC error.
at http://192.168.1.190:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:162276:293 in _createSuperInternal
at node_modules/@magic-sdk/provider/dist/cjs/index.js:1:20981 in <global>
at node_modules/@magic-sdk/provider/dist/cjs/index.js:5:3638 in overlay.on$argument_1
```
### 💻 Code Sample
See steps to reproduce 

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  "@magic-sdk/react-native": "^8.2.1" and "magic-sdk": "^8.1.1"
| Browser          |  Chrome Version 102.0.5005.61 (Official Build) (arm64)
| `yarn`           | 1.22.18
| Operating System | MacOS Monterey 12.2.1

**Comment by michaelhly** [comment]
Issue was b/c I had `testmode` turned toggled. What is test mode?

**Comment by bethhowell123** [comment]
Hey @michaelhly thanks for updating with a resolution!  `testMode` allows you to streamline your integration testing by eliminating the need to navigate to your mail client and click an actual Magic Link.  More details in our docs here: https://magic.link/docs/introduction/test-mode

Let us know if you have any additional questions!
