### ISSUE TITLE
TestMode not working with login and test email

### ISSUE THREAD

**Issue by drewdrewthis** [magiclabs/magic-js#407]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When `testMode` is enabled, the login doesn't work and creates an error on the service (backend?). The login fails:

```
      error_code: 'RESOURCE_NOT_FOUND',
      message: 'Given issuer resource not found.',
```
Set up according to tutorial:
https://magic.link/posts/magic-link-nextjs

Followed all directions from the documentation:
https://magic.link/docs/auth/introduction/test-mode

### 🧩 Steps to Reproduce

1. Enable test mode:
```
      const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY, {
        testMode: true,
      });
```

2. Use magic link test password:
test+success@magic.link

Submit form.

### 🤔 Expected behavior

Logs the user in

### 😮 Actual behavior

Stack trace:
```
MagicAdminSDKError: Magic Admin SDK Error: [SERVICE_ERROR] A service error occurred while communicating with the Magic API. Check the `data` key of this error object to see nested errors with additional context.
    at new MagicAdminSDKError (/Users/hope/workspace/kulaa-nextjs-contentful/node_modules/.pnpm/@magic-sdk+admin@1.8.0/node_modules/@magic-sdk/admin/dist/cjs/core/sdk-exceptions.js:22:28)
    at Object.createServiceError (/Users/hope/workspace/kulaa-nextjs-contentful/node_modules/.pnpm/@magic-sdk+admin@1.8.0/node_modules/@magic-sdk/admin/dist/cjs/core/sdk-exceptions.js:62:12)
    at /Users/hope/workspace/kulaa-nextjs-contentful/node_modules/.pnpm/@magic-sdk+admin@1.8.0/node_modules/@magic-sdk/admin/dist/cjs/utils/rest.js:85:48
    at step (/Users/hope/workspace/kulaa-nextjs-contentful/node_modules/.pnpm/@magic-sdk+admin@1.8.0/node_modules/@magic-sdk/admin/dist/cjs/utils/rest.js:33:23)
    at Object.next (/Users/hope/workspace/kulaa-nextjs-contentful/node_modules/.pnpm/@magic-sdk+admin@1.8.0/node_modules/@magic-sdk/admin/dist/cjs/utils/rest.js:14:53)
    at fulfilled (/Users/hope/workspace/kulaa-nextjs-contentful/node_modules/.pnpm/@magic-sdk+admin@1.8.0/node_modules/@magic-sdk/admin/dist/cjs/utils/rest.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'SERVICE_ERROR',
  data: [
    {
      data: {},
      error_code: 'RESOURCE_NOT_FOUND',
      message: 'Given issuer resource not found.',
      status: 'failed'
    }
  ]
}
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  "^11.0.0"
| Browser          | Chrome Version 108.0.5359.124 (Build officiel) (arm64)
| `pnpm`           | 7.18.2
| Operating System | macOS 12.5.1

**Comment by ayv8er** [comment]
Hi @drewdrewthis, testMode is only supported on our client-side SDK. The resolved didToken from the loginWithMagicLink method isn't supported in our server-side SDK. We'll aim to make this more clear in the documentation and will take steps to make this more obvious.

**Comment by drewdrewthis** [comment]
@ayv8er thanks for the response. I believe I am using the client-side SDK 'magic-sdk' --- it's running in the browser. 

This should work, should it not?

```
import { Magic } from "magic-sdk";
...
const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY, {
  testMode: true,
});

const didToken = await magic.auth.loginWithMagicLink({
  email: "test+success@magic.link",
});
 ```
