### ISSUE TITLE
CORS error when Magic requests Segment.com CDN

### ISSUE THREAD

**Issue by AndrewCer** [magiclabs/magic-js#443]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

As of today, we are getting a CORS error when magic attempts to request `https://cdn.segment.com/v1/projects/JXVPCvqPMFxMoX8CaxEraTenlgziQtVK/settings`. We believe that this is coming from the Magic SDK because when we remove the package from our app, the error no longer exists.

This is a blocking issue as it prevents other Magic SDK methods from working.

This issue cropped up in our production, test, and dev environments. Of which, production has not received changes for a few days.

### 🧩 Steps to Reproduce

1. Spin up an angular app `ng new magic-test-app`
2. `npm install magic-sdk @magic-ext/connect`
3.

```js
import { Magic } from 'magic-sdk';

const magicLink = new Magic(<magicPublicKey>);

magicLink.preload(); // or invoke any Magic method.
```

### 🤔 Expected behavior

No CORS error when Magic does a request to cdn.segment.com.

### 😮 Actual behavior

`Refused to connect to 'https://cdn.segment.com/v1/projects/JXVPCvqPMFxMoX8CaxEraTenlgziQtVK/settings' because it violates the following Content Security Policy directive: "connect-src 'self`

```js
app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2 Refused to connect to 'https://cdn.segment.com/v1/projects/JXVPCvqPMFxMoX8CaxEraTenlgziQtVK/settings' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.magic.link/ https://*.fortmatic.com/ https://*.alchemyapi.io/ wss://*.ws.alchemyapi.io/ https://*.infura.io/ https://*.alchemy.com/ https://*.quiknode.pro/ https://*.maticvigil.com/ https://*.binance.org/ https://*.moralis.io/ https://*.matic.network/ https://*.binance.org:8545/ https://gbscache.magic.link/ https://cognito.us-west-2.amazonaws.com/ https://kms.us-west-2.amazonaws.com/ https://cognito-identity.us-west-2.amazonaws.com/ https://*.google.com/ https://www.google-analytics.com/ https://api.segment.io/ https://api.amplitude.com/ https://*.datadoghq.com/ https://*.browser-intake-datadoghq.com/ wss://*.peerjs.com https://*.launchdarkly.com/ wss://*.bridge.walletconnect.org https://registry.walletconnect.com/ wss://www.walletlink.org/rpc https://node1.fairmint.co/ https://beefledgerwallet.com:8544/ https://core.bloxberg.org/ https://node.moonnet.space/ https://goerli.zed.run/ https://rpc.xdaichain.com/ https://matic-mumbai.chainstacklabs.com/ https://api.niftys.com https://api.staging.niftys.com https://palm.eth.niftys.com:8545 https://palm-testnet.eth.niftys.com:8545 https://*.palm.niftys.com:8545 wss://*.palm.niftys.com:8546 https://*.rpc.thirdweb.com/ https://*.rpc.cayg.app/ https://rpc.toronto.sx.technology https://rpc.sx.technology https://apis.ankr.com/ https://bsc.getblock.io/ https://rpc.ankr.com/ https://*.pokt.network/ https://dblockchain.akru.co https://blockchain.akru.co https://avax.getblock.io/ http://localhost:*/ http://127.0.0.1:*/ ws://127.0.0.1:*/ https://evm.cronos.org/ https://evm-t3.cronos.org/ https://*.onflow.org https://rpc.fragmynt.network/ https://galway-rpc.fragmynt.network/ https://bicon.net.solidwallet.io/ https://ctz.solidwallet.io/ https://berlin.net.solidwallet.io/ https://api.harmony.one/ https://api.s0.t.hmny.io/ https://api.s0.b.hmny.io/ https://tezos-prod.cryptonomic-infra.tech/ https://tezos-dev.cryptonomic-infra.tech/ https://mainnet.api.tez.ie https://hangzhounet.api.tez.ie https://ithacanet.ecadinfra.com wss://rpc.polkadot.io wss://kusama-rpc.polkadot.io/ https://sokol.poa.network/ https://xdai.poanetwork.dev/ https://*.skalelabs.com https://*.skale.network https://*.matic.today/ https://polygon-rpc.com/ https://api.mainnet-beta.solana.com https://devnet.solana.com https://api.devnet.solana.com https://testnet.solana.com https://api.testnet.solana.com https://api.zilliqa.com/ https://dev-api.zilliqa.com/ https://api.avax.network/ https://api.avax-test.network/ https://testapi.avax.network https://dai.poa.network/ https://rpc.gnosischain.com https://xdai.1hive.org/ https://*.optimism.io https://alfajores-forno.celo-testnet.org https://forno.celo.org https://bsc-dataseed1.defibit.io/ https://bsc-dataseed1.ninicoin.io/ https://*.moonbeam.network https://rpcapi.fantom.network https://rpc.testnet.fantom.network/ https://rpc.ftm.tools/ https://*.arbitrum.io/ https://test.confluxrpc.com https://main.confluxrpc.com https://stage2-api.zksync.dev/ https://*.telos.net/ https://*.aurora.dev https://*.metis.io https://evmexplorer.velas.com/ https://evmexplorer.testnet.velas.com/ https://evmexplorer.devnet.velas.com/ https://arctic-rpc.icenetwork.io:9933 wss://arctic-rpc.icenetwork.io:9944 https://rpc.tst.publicmint.io:8545 https://rpc.publicmint.io:8545 https://exchainrpc.okex.org/ https://*.p2pify.com/ https://*.myhbarwallet.com https://scoville-rpc.chiliz.com/ https://gwan-ssl.wandevs.org:56891/".
```

The originator of below error is: `https://assets.auth.magic.link/static`

```js
app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2 Refused to connect to 'https://cdn.segment.com/v1/projects/JXVPCvqPMFxMoX8CaxEraTenlgziQtVK/settings' because it violates the document's Content Security Policy.

app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2 [analytics.js] Failed to load Analytics.js TypeError: Failed to fetch
    at Fr.t (app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2:857695) <-- originator is https://assets.auth.magic.link/static
    at i (app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2:854234)
    at Cn.t (app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2:768757)
    at i (app.chunk~vendor~fad58de7366495db4650cfefac2fcd61.1d4a8e21cd317cbe60c0.js:2:767269)
    at o (analytics.min.js:1:40387)
    at index.ts:88:26
    at tslib.es6.js:103:23
    at Object.next (tslib.es6.js:108:37)
    at tslib.es6.js:80:8
    at new Promise (<anonymous>)
```

### 💻 Code Sample

Service from within our app:

```js
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';

import { ConnectExtension } from '@magic-ext/connect';
import { Magic } from 'magic-sdk';

@Injectable({
    providedIn: 'root'
})
export class MagicLinkService {
    private magicLink = new Magic(environment.magicPublicKey, {
            extensions: [new ConnectExtension()],
            // Network doesn't matter, happens with both.
            network: {
                rpcUrl: 'https://matic-mumbai.chainstacklabs.com',
                chainId: 80001,
            },
            // network: {
            //     rpcUrl: 'https://polygon-rpc.com/',
            //     chainId: 137,
            // }
        });

    constructor() {
        // Then invoke any magic method
        this.magicLink.preload();

        // Sample from elsewhere in the app that also throws same error:
        // const provider = new ethers.providers.Web3Provider(this.magicLink.rpcProvider as any);
        // const signer = provider.getSigner();
    }
}

```

### 🌎 Environment

| Software             | Version(s)              |
| -------------------- | ----------------------- |
| `magic-sdk`          | `^13.1.0`               |
| `@magic-ext/connect` | `^6.2.0`                |
| Browser              | Firefox, Chrome, Safari |
| `npm`                | 8.6.0                   |
| Operating System     | Mac, Windows, iOS       |

**Comment by ayv8er** [comment]
@AndrewCer I can confirm this error did come up for me while testing as well.
However, it wasn't blocking other SDK methods from working properly.
Could you explain which methods were blocked as a result of this?

**Comment by AndrewCer** [comment]
Hey @ayv8er thanks for responding! I've been trying to re-test this today and I'm not seeing the issue on any of our envs. Maybe it was a Segment issue that they resolved? 

For historic context:

We are using Magic Connect. So the authentication/sign-in with email modal would work fine. However, provider methods would error out and block our app from functioning.

```js
const magic = Magic(<apiKey>, {
          extensions: [new ConnectExtension()],
          network: <chainNetwork>,
        })
const emailProvider = new ethers.providers.Web3Provider(magic.rpcProvider);
const emailSigner = emailProvider.getSigner();

const signature = await emailSigner.signMessage(<signatureMessage>); // <--- Blocked
```

Screenshot of error from above code
![image](https://user-images.githubusercontent.com/12091227/215343312-73688992-190b-4f17-8ede-a7af588346fc.png)

Again, the initial tests look good and we are not seeing the error anymore. I'll report back here once we finish testing.

**Comment by AndrewCer** [comment]
Looks resolved on our end.
